### ISSUE TITLE
一些建议，望采纳

### ISSUE THREAD

**Issue by Moe8383** [liuhangbin/fast115#1]
感谢大佬的封装工具，希望增加以下功能：
1. 仅对未生成过strm（未标星）的文件进行增量处理
2. 增加选项：是否处理图片、nfo、字幕文件

**Comment by liuhangbin** [comment]
> 仅对未生成过strm（未标星）的文件进行增量处理

代码里面应该[有处理](https://github.com/liuhangbin/fast115/blob/main/app/utils/download.py#L130)，已有的文件会跳过处理

> 增加选项：是否处理图片、nfo、字幕文件

可以，回头有空加上

**Comment by Moe8383** [comment]
> 代码里面应该有处理，已有的文件会跳过处理

我意思是本地strm已经被刮削移动后，网盘的已标星文件夹能不能选择不处理（选项）？

**Comment by liuhangbin** [comment]
> 我意思是本地strm已经被刮削移动后，网盘的已标星文件夹能不能选择不处理（选项）？

这个不清楚，python-115有这个功能吗?

**Comment by Moe8383** [comment]
> 这个不清楚，python-115有这个功能吗?
> 
我看群里说是可以哦

**Comment by wxrbbs** [comment]
可以的，隔壁小星那个版本就可以增量扫。

搭车建议：
1、顺便把端口也可以自定义。一般都用host模式相对快，很多docker避免冲突。
2、小星那个版本也可以自动比对后删除无效strm，望也加入谢谢！
3、自定义要复制的内容，小星那版本就是自己手动添加后缀名方式解决的。

**Comment by liuhangbin** [comment]
>  1、顺便把端口也可以自定义。一般都用host模式相对快，很多docker避免冲突。
可以
> 2、小星那个版本也可以自动比对后删除无效strm，望也加入谢谢！

这个怎么处理？ 是本地的文件移动了还是云端的文件移动了？

> 3、自定义要复制的内容，小星那版本就是自己手动添加后缀名方式解决的。

OK, 是只针对图片，字幕吗？ 还是说所有类型的文件都要处理？

**Comment by liuhangbin** [comment]
>  2、小星那个版本也可以自动比对后删除无效strm，望也加入谢谢！ 3、自定义要复制的内容，小星那版本就是自己手动添加后缀名方式解决的。

你好，方便的话加fast115的群然后详细聊吧。我没买小星的，不知道具体怎么设置的。

**Comment by liuhangbin** [comment]
Fixed by ddc72f6539de ("docker: update to 0.1.4")
