### ISSUE TITLE
字幕问题

### ISSUE THREAD

**Issue by wxrbbs** [liuhangbin/fast115#2]
貌似外挂字幕不能加载，jellyfin+建政大佬8091端口的302，jf直连模式都是可以播放302就是外挂字幕不能加载。

**Comment by liuhangbin** [comment]
这个好像是老问题了，jellyfin 302 不支持加载字幕

**Comment by wxrbbs** [comment]
你好，jellyfin用建政大佬的302是可以加载外挂字幕的，他是在播放预读时候自动复制字幕到缓存的，然后推送的。（至于字幕兼容问题无法加载的是格式等其它问题了）

![image](https://github.com/user-attachments/assets/313caaeb-53ea-415a-b0c4-28a18eff026b)


如果你302服务端没用做字幕处理的，是无法调用的，strm只有单视频文件的。

**Comment by liuhangbin** [comment]
大佬的代码都是闭源的，不知道怎么处理的...

**Comment by rockbenben** [comment]
能不能让 fast115 设置页面自行选择本地 strm 或 302 到 115，设置本地strm是不是可以解决字幕挂载问题

**Comment by liuhangbin** [comment]
> 你好，jellyfin用建政大佬的302是可以加载外挂字幕的，他是在播放预读时候自动复制字幕到缓存的，然后推送的。（至于字幕兼容问题无法加载的是格式等其它问题了）

我这周研究一下看怎么调用大佬的dav 302, 现在用的是mini版的。

**Comment by liuhangbin** [comment]
我这里用emby测试，没有问题，客户端或者网页都可以加载字幕。
